@echo off
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" >nul
if errorlevel 1 exit /b %errorlevel%
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /std:c++17 /EHsc /O2 /fp:strict /MD /utf-8 /DGGML_SHARED /DGGML_BACKEND_SHARED /I"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\source\llama.cpp-semantic\ggml\include" /I"E:\cuda\include" /I"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\source\llama.cpp-semantic\ggml\src" "F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\stream_event_probe.cpp" /Fe:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\operator-surface-probe.exe" /Fo:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\operator-surface-probe.obj" /link /LIBPATH:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\source\llama.cpp-native-thread-control\build-native-thread-control\ggml\src" /LIBPATH:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\source\llama.cpp-semantic\build-semantic-direct\ggml\src" /LIBPATH:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\source\llama.cpp-semantic\build-semantic-direct\ggml\src\ggml-cuda" /LIBPATH:"E:\cuda\lib\x64" ggml-base.lib ggml-cpu.lib ggml-cuda.lib bcrypt.lib cudart.lib
if errorlevel 1 exit /b %errorlevel%
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /std:c++17 /EHsc /O2 /fp:strict /MD /utf-8 "F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\environment_echo.cpp" /Fe:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\environment-echo.exe" /Fo:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\environment-echo.obj"
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /std:c++17 /EHsc /O2 /fp:strict /MD /utf-8 /DGGML_SHARED /DGGML_BACKEND_SHARED /I"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\source\llama.cpp-semantic\ggml\include" "F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\reference_host.cpp" /Fe:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\reference-host.exe" /Fo:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\reference-host.obj" /link /LIBPATH:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\source\llama.cpp-native-thread-control\build-native-thread-control\ggml\src" /LIBPATH:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\source\llama.cpp-semantic\build-semantic-direct\ggml\src" ggml-base.lib
if errorlevel 1 exit /b %errorlevel%
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /std:c++17 /EHsc /O2 /MD /utf-8 "F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\module_guard_host.cpp" /Fe:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\module-guard-host.exe" /Fo:"F:\codex_project\37_LLMsim\heterollm-sim-4.0.0\artifacts\development\native_long_grid_135_20260915\optimization_loop\round_016\operator_probe\r3\module-guard-host.obj"
exit /b %errorlevel%
