/** Export true frontend preset selections for matched GGUF/native validation.
 * Dedicated controls are used where present; absent controls are explicitly
 * configured in an exported JSON file and imported via the UI. No hidden state
 * assignments or direct POSTs are used. The initial textarea retry is recorded.
 */
const {chromium}=require('C:/Users/A/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..');const OUT=path.join(ROOT,'docs/gguf_preset_native_validation_2026-10-08');
const base=path.join(OUT,'base');fs.mkdirSync(base,{recursive:true});
const catalog=JSON.parse(fs.readFileSync(path.join(OUT,'cases.json'),'utf8'));
const selectedArg=process.argv.indexOf('--cases');const selectedCases=selectedArg<0?catalog.cases:catalog.cases.filter(item=>process.argv[selectedArg+1].split(',').includes(item.case_id));assert.ok(selectedCases.length,'Requested cases not found');
const nativeModels=JSON.parse(fs.readFileSync(path.join(OUT,'model_manifest.json'),'utf8')).models;
const scratch=path.resolve(ROOT,'../../_scratch/37-gguf-ui-base-import');fs.mkdirSync(scratch,{recursive:true});
function comparable(model){const x=structuredClone(model);delete x.metadata.ui;delete x.metadata.artifact_id;delete x.graph.attributes.ui;x.graph.source_operators??=[];x.graph.sub_operators??=[];x.graph.tensors.sort((a,b)=>a.tensor_id.localeCompare(b.tensor_id));return x;}
const REVISION='d3146f2b56c2db4711ac8391871c9e529d1946d7';
let manifest={schema:'heterollm.frontend-preset-preparation/v1',url:'http://127.0.0.1:8794/',status:'in_progress',submission:'Not submitted: graph structure and independently measured costs must be bound first.',hardware_preset:catalog.hardware_preset,methodology:'Real Edge browser and frontend controls; Frontend export, explicitly edited auxiliary JSON for runtime options without dedicated controls, frontend file import, validate and export buttons. No hidden state mutation or direct API submission.',previous_attempts:[{case_id:'qwen3_0_6b_f16',method:'Advanced JSON editor',status:'completed then replaced below to add exact native model path'},{case_id:'qwen3_1_7b_q8_0',method:'Advanced JSON editor',status:'automation textarea fill timed out at 90 seconds; no page error, not classified as a product bug'}],cases:[]};
if(selectedArg>=0&&fs.existsSync(path.join(OUT,'ui_preparation.json'))){manifest=JSON.parse(fs.readFileSync(path.join(OUT,'ui_preparation.json'),'utf8'));manifest.status='in_progress';manifest.cases=manifest.cases.filter(item=>!selectedCases.some(selected=>selected.case_id===item.case_id));}
function save(){fs.writeFileSync(path.join(OUT,'ui_preparation.json'),JSON.stringify(manifest,null,2)+'\n');}
async function fill(page,selector,value){await page.locator(selector).fill(String(value));await page.locator(selector).press('Tab');}
async function runtime(page,field,value){const control=page.locator(`[data-llama-runtime-field="${field}"]`);if(!await control.isVisible()){await control.locator('xpath=ancestor::details/summary').click();}await fill(page,`[data-llama-runtime-field="${field}"]`,value);}
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{for(const item of selectedCases){
  const page=await browser.newPage({acceptDownloads:true});page.setDefaultTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const started=Date.now();const record={...item,page_errors:errors,actions:[]};manifest.cases.push(record);save();
  try{
   await page.goto(manifest.url);await page.waitForFunction(()=>state.scenario!==null);
   await page.locator('[data-view="model"]').click();await page.locator('#modelPresetsButton').click();await page.locator('#presetSearchInput').fill(item.preset_id);await page.locator(`[data-apply-preset="${item.preset_id}"]`).click();await page.waitForFunction(id=>state.scenario.model.metadata?.model_preset_id===id,item.preset_id);record.actions.push('Select model preset through model card');
   await page.locator('[data-view="architecture"]').click();await page.locator('#hardwarePresetsButton').click();await page.locator('#hardwarePresetArchitectureTab').click();await page.locator(`[data-load-architecture-preset="${catalog.hardware_preset}"]`).click();await page.waitForFunction(()=>state.scenario.hardware.components.length>0);record.actions.push('Select local hardware architecture preset through hardware card');
   await page.locator('[data-view="mapping"]').click();await page.locator('select[data-llama-runtime-mode]').selectOption('llama_cpp');await page.locator('[data-llama-runtime-field="device_memory_tiering"]').uncheck();
   for(const [field,value]of Object.entries({gpu_layers:-1,batch:512,ubatch:512,context:768,parallel:1})){await runtime(page,field,value);}record.actions.push('Set llama.cpp mode, full GPU layers, batch/ubatch 512, context 768, parallel 1, tiering disabled via controls');
   await page.locator('[data-view="workload"]').click();await fill(page,'[data-request-field="prompt_tokens"]',512);await fill(page,'[data-request-field="output_tokens"]',128);record.actions.push('Set request 512 prompt and 128 output tokens via request table');
   const originalDownload=page.waitForEvent('download');await page.locator('#exportButton').click();const originalPath=path.join(scratch,`${item.case_id}.original.json`);await(await originalDownload).saveAs(originalPath);const payload=JSON.parse(fs.readFileSync(originalPath,'utf8'));const selectedModel=JSON.stringify(payload.model);record.original_ui_export_path=originalPath;
   payload.name=`frontend-gguf-native/${item.case_id}/512-128`;
   Object.assign(payload.profiles.llama_cpp,{threads:16,threads_batch:16,flash_attn:false,kv_type_k:'f16',kv_type_v:'f16',kv_unified:true,cont_batching:true,warmup:true,seed:0,mmap:true,mlock:false,op_offload:true,split_mode:'layer',main_gpu:0});
   payload.profiles.fusion.flash_attention=false;
   payload.placement.parallel.rank_mapping=[{rank:0,component_id:'gpu0',tp_rank:0,pp_rank:0,ep_rank:0,memory_component_id:'gddr0',cim_component_id:null}];
   Object.assign(payload.placement.kv_policy,{cache_component:'gddr0',offload_component:null,offload_ratio:0,dtype:'fp16',layout_mode:'legacy_single',kv_unified:true});
   payload.profiles.host_output={target_component_id:'hostmem0',vocabulary_size:payload.model.metadata.symbols.V,logits_dtype:'fp32',logits_element_bytes:4,allocation_semantics:'unspecified'};
   payload.profiles.sampling={mode:'greedy',temperature:0,implementation:'llama_cpp_cpu_chain',top_k:40,top_p:0.95,min_p:0.05,min_keep:0};
   const native=nativeModels.find(m=>m.case_id===item.case_id);assert.ok(native?.model_path,'Exact native model path required');const nativeParity={native_model_path:native.model_path,native_model_file:path.basename(native.model_path),native_runtime_context:{requested:768,effective_required:768}};Object.assign(payload.workload.metadata,nativeParity);Object.assign(payload.workload.requests[0].metadata,nativeParity);payload.workload.metadata.native_ctx_checkpoints=0;
   payload.workload.metadata.native_runtime_context={requested:768,effective_required:768};
   payload.workload.metadata.native_output_contract_evidence={source_revision:REVISION,configuration_source:'common/common.h common_params_sampling defaults; request temperature=0',logits_source:'llama-context.cpp: n_outputs*n_vocab*sizeof(float) asynchronous host copy',sampling_source:'common/sampling.cpp: ordered CPU sampler chain',native_settings_record:null,measured_latency_used:false,settings_observed:false,remaining_partial_costs:['completion interrupt latency','sampler heap repair/sort/branch/cache/compiler behavior','disabled sampler and EOS logit-bias overhead','GET_ROWS F16 conversion compute']};
   assert.equal(JSON.stringify(payload.model),selectedModel,'Advanced configuration must not replace or mutate the GGUF model');
   assert.equal(payload.workload.requests.length,1);assert.equal(payload.workload.mtp,null);
   record.advanced_json_configuration={name:payload.name,llama_cpp:payload.profiles.llama_cpp,fusion:payload.profiles.fusion,rank_mapping:payload.placement.parallel.rank_mapping,kv_policy:payload.placement.kv_policy,host_output:payload.profiles.host_output,sampling:payload.profiles.sampling,native_model_path:native.model_path,native_model_file:path.basename(native.model_path),native_ctx_checkpoints:0,native_runtime_context:payload.workload.metadata.native_runtime_context,native_output_contract_evidence:payload.workload.metadata.native_output_contract_evidence};
   const importPath=path.join(scratch,`${item.case_id}.configured.json`);fs.writeFileSync(importPath,JSON.stringify(payload,null,2)+'\n');record.auxiliary_config_path=importPath;const choosePromise=page.waitForEvent('filechooser');await page.locator('#importButton').click();const chooser=await choosePromise;const normPromise=page.waitForResponse(r=>r.url().endsWith('/api/normalize')&&r.request().method()==='POST');await chooser.setFiles(importPath);const normalized=await normPromise;if(!normalized.ok())throw new Error('Auxiliary JSON import normalization failed: '+await normalized.text());await page.waitForFunction(name=>state.scenario.name===name,payload.name);record.actions.push('Export original frontend scenario; edit only explicitly recorded runtime fields in auxiliary JSON; import it through frontend file chooser and backend normalization');
   const validationPromise=page.waitForResponse(r=>r.url().endsWith('/api/validate')&&r.request().method()==='POST');await page.locator('#validateButton').click();const validation=await(await validationPromise).json();record.validation=validation;if(!validation.valid)throw new Error('Validation rejected '+JSON.stringify(validation));
   const downloadPromise=page.waitForEvent('download');await page.locator('#exportButton').click();const download=await downloadPromise;const filename=`scenario_${item.case_id}_512_128.json`;await download.saveAs(path.join(base,filename));const exported=JSON.parse(fs.readFileSync(path.join(base,filename),'utf8'));
   record.model_serialization_identical=JSON.stringify(exported.model)===selectedModel;assert.deepStrictEqual(comparable(exported.model),comparable(JSON.parse(selectedModel)),'Model execution semantics and GGUF metadata must remain unchanged');record.model_semantics_preserved=true;record.model_comparison='comparable_cuda_graph_model-equivalent: remove only UI/artifact labels, normalize empty source/sub-operator registries and sort tensors by ID; preserve operator order and every executable tensor/metadata field';record.model_preset_id=exported.model.metadata.model_preset_id;record.model_source=exported.model.metadata.gguf_preset_origin;record.export_path=path.join(base,filename);record.export_bytes=fs.statSync(record.export_path).size;record.actions.push('Validate and export using frontend buttons');record.status='completed';record.wall_seconds=(Date.now()-started)/1000;
   assert.equal(record.model_preset_id,item.preset_id);assert.equal(errors.length,0);save();console.log(JSON.stringify({case_id:item.case_id,status:record.status,export_path:record.export_path,page_errors:errors,model_preserved:record.model_semantics_preserved}));
  }catch(e){record.status='failed';record.error=e.message.split('\n')[0];save();throw e;}finally{await page.close();}
 }
 manifest.status='completed';save();}finally{await browser.close();}
})().catch(e=>{console.error(e.message.split('\n')[0]);process.exitCode=1});
