/** Tiny frontend smoke cases after source-path fixes; never overwrites 512/128 base. */
const {chromium}=require('C:/Users/A/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..');const OUT=path.join(ROOT,'docs/gguf_preset_native_validation_2026-10-08');
const scratch=path.resolve(ROOT,'../../_scratch/37-gguf-ui-base-import');const outcomes=[];
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{for(const slug of ['qwen2_5_0_5b_q4_k_m','llama3_2_1b_q4_k_m']){
 const payload=JSON.parse(fs.readFileSync(path.join(OUT,'base',`scenario_${slug}_512_128.json`),'utf8'));payload.name=`frontend-gguf-source-smoke/${slug}/8-2`;payload.workload.requests[0].prompt_tokens=8;payload.workload.requests[0].output_tokens=2;payload.workload.prompt_tokens=8;payload.workload.output_tokens=2;
 const input=path.join(scratch,`${slug}.smoke-8-2.json`);fs.writeFileSync(input,JSON.stringify(payload,null,2)+'\n');const record={case_id:slug,workload:'8/2; context 768; other runtime settings match base',input_path:input,accuracy_comparison:false,page_errors:[],status:'preparing'};outcomes.push(record);
 const save=()=>fs.writeFileSync(path.join(OUT,'ui_source_fix_smoke.json'),JSON.stringify(outcomes,null,2)+'\n');save();
 const page=await browser.newPage();page.setDefaultTimeout(120000);page.on('pageerror',e=>record.page_errors.push(e.message));page.on('dialog',d=>d.accept());const start=Date.now();
 try{
 await page.goto('http://127.0.0.1:8794/');await page.waitForFunction(()=>state.scenario!==null);const chooserPromise=page.waitForEvent('filechooser');await page.locator('#importButton').click();const chooser=await chooserPromise;const normPromise=page.waitForResponse(r=>r.url().endsWith('/api/normalize')&&r.request().method()==='POST');await chooser.setFiles(input);const norm=await normPromise;assert.ok(norm.ok(),await norm.text());await page.waitForFunction(name=>state.scenario.name===name&&!state.busy,payload.name);
 const validationPromise=page.waitForResponse(r=>r.url().endsWith('/api/validate')&&r.request().method()==='POST');await page.locator('#validateButton').click();record.validation=await(await validationPromise).json();assert.equal(record.validation.valid,true);
 await page.locator('#runButton').click();await page.waitForFunction(()=>!state.busy&&state.runEstimate!==null);const createdPromise=page.waitForResponse(r=>r.url().endsWith('/api/run-jobs')&&r.request().method()==='POST');await page.locator('#startRunJobButton').click();const response=await createdPromise;record.job_created=await response.json();record.job_id=record.job_created.job_id;assert.ok(response.ok(),JSON.stringify(record.job_created));fs.writeFileSync(path.join(OUT,`ui_smoke_${slug}_submission.json`),JSON.stringify(response.request().postDataJSON(),null,2)+'\n');save();
 for(;;){const status=await page.evaluate(()=>({status:state.runJob?.status,error:state.runJob?.error,progress:state.runJob?.progress}));if(['completed','failed','cancelled'].includes(status.status)){const result=await page.evaluate(()=>state.runJob);fs.writeFileSync(path.join(OUT,`ui_smoke_${slug}_result.json`),JSON.stringify(result,null,2)+'\n');record.status=status.status;record.error=status.error;assert.equal(status.status,'completed',JSON.stringify(status.error));break;}if(Date.now()-start>300000)throw new Error('Smoke exceeded five minutes');await page.waitForTimeout(1000);}
 assert.equal(record.page_errors.length,0);record.wall_seconds=(Date.now()-start)/1000;save();console.log(JSON.stringify({case_id:slug,status:record.status,page_errors:record.page_errors,wall_seconds:record.wall_seconds}));
 }catch(error){record.status='failed';record.error=error.message.split('\n')[0];save();throw error;}finally{await page.close();}
 }}finally{await browser.close();}})().catch(error=>{console.error(error.message.split('\n')[0]);process.exitCode=1});
